name: simpleble_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

dependencies:
  ffi: 2.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  ffigen: ^11.0.0

ffigen:
  output: 'lib/generated/generated_bindings.dart'
  headers:
    entry-points:
        - 'simpleble_c/simpleble.h'
    include-directives:
      - 'simpleble_c/**.h'